- name: Install python packages
  command: pip3 install {{ item }}
  become: yes
  with_items:
    - requests
    - tablib
    - pyyaml
    - records
    - pymysql
    - cherrypy
    # only for tests
    - pytest
    - pytest-cov
    - requests_mock
